# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block; everything else may go below.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

# User configuration
export LANG=en_US.UTF-8
export LC_ALL=en_US.UTF-8
export EDITOR='nvim-client -f'
export ZSH=$HOME/.oh-my-zsh
export UPDATE_ZSH_DAYS=1
export TERM=xterm-256color

# Color LESS output
export LESS="-R"
export LESSOPEN="| bat %s"

# Vi-Mode
export KEYTIMEOUT=1
export RPS1="%{$reset_color%}" # Must be before oh-my-zsh source

# Oh My ZSH Stuff
skip_global_compinit=1

# Cache completion list for faster load times
autoload -Uz compinit
typeset -i updated_at=$(date +'%j' -r ~/.zcompdump 2>/dev/null || stat -f '%Sm' -t '%j' ~/.zcompdump 2>/dev/null)
if [ $(date +'%j') != $updated_at ]; then
  compinit
else
  compinit -C -i
fi

COMPLETION_WAITING_DOTS="true"
DISABLE_UNTRACKED_FILES_DIRTY="true"
HIST_STAMPS="dd.mm.yyyy"
# ZSH_THEME="spaceship"
ZSH_THEME="powerlevel10k/powerlevel10k"
plugins=(
  colored-man-pages
  postgres
  git
  gitfast
  last-working-dir
  common-aliases
  history-substring-search
  zsh-autosuggestions
  zsh-syntax-highlighting
  # zsh-interactive-cd
  fzf-tab
)

# History
HISTFILE=$HOME/.cache/zsh/history
HISTSIZE=100000
SAVEHIST=$HISTSIZE
setopt hist_ignore_all_dups # remove older duplicate entries from history
setopt hist_reduce_blanks   # remove superfluous blanks from history items
setopt inc_append_history   # save history entries as soon as they are entered
setopt share_history        # share history between different instances of the shell

# Don't ask about updating ohmyzsh - do it automatically
DISABLE_UPDATE_PROMPT=true

# Sourcing other files
source $ZSH/oh-my-zsh.sh
source $HOME/.config/zsh/aliases
source $HOME/.config/zsh/functions
source $HOME/.config/zsh/prompt

# ZSH Options
setopt auto_cd       # cd by typing the dir name if its not a command name
setopt correct_all   # autocorrect commandsl
setopt auto_list     # automatically list choices on ambiguous completion
setopt auto_menu     # automatically use menu completion
setopt always_to_end # move cursor to end if word had one match
set completion-ignore-case on
set show-all-if-ambiguous on

# History Substring Search
bindkey '^[[A' history-substring-search-up
bindkey '^[[B' history-substring-search-down

# Use Homebrews SSL for ruby
export RUBY_CONFIGURE_OPTS="--with-openssl-dir=$(brew --prefix openssl@1.1)"

# Bitwarden
export BW_SESSION="kPScZ7cZOfPL1RmihVMAQiK6Yk0OW6sJ9G/qhr7GN/KGvHs9Otnd3u7p1FwjDnzVMB0z7rZefG03JbPexTLtnA=="

# Autocompletion and Kitty
zmodload -i zsh/complist
kitty + complete setup zsh | source /dev/stdin

export PATH="/usr/local/opt/python/libexec/bin:$PATH"
export PATH="/usr/local/opt/sqlite/bin:$PATH"
export PATH="/usr/local/opt/curl/bin:$PATH"
export PATH="$HOME/.yarn/bin:$HOME/.config/yarn/global/node_modules/.bin:$PATH"
export PATH="./bin:./node_modules/.bin:${PATH}:/usr/local/sbin"
export PATH="/snap/bin:$PATH"
export PATH="$HOME/.local/bin:$PATH"

# Launch TMUX if it's not active
[ -z "$TMUX" ] && ( tmux attach -t default || tmux new -s default )
# Close connection after TMUX terminates
[ -z "$TMUX" ] && clear && exit

# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh
