#!/bin/env sh

# send window to desktop and follow focus
cmd + alt - 1 : yabai -m window --space  1; yabai -m space --focus 1
cmd + alt - 2 : yabai -m window --space  2; yabai -m space --focus 2
cmd + alt - 3 : yabai -m window --space  3; yabai -m space --focus 3
cmd + alt - 4 : yabai -m window --space  4; yabai -m space --focus 4
cmd + alt - 5 : yabai -m window --space  5; yabai -m space --focus 5
cmd + alt - 6 : yabai -m window --space  6; yabai -m space --focus 6
cmd + alt - 7 : yabai -m window --space  7; yabai -m space --focus 7
cmd + alt - 8 : yabai -m window --space  8; yabai -m space --focus 8
cmd + alt - 9 : yabai -m window --space  9; yabai -m space --focus 9
cmd + alt - 0 : yabai -m window --space  0; yabai -m space --focus 0

# send window to monitor and follow focus
cmd + alt + shift - 1  : yabai -m window --display 1; yabai -m display --focus 1; yabai -m space --balance
cmd + alt + shift - 2  : yabai -m window --display 2; yabai -m display --focus 2; yabai -m space --balance

# Set Window Focus
cmd + ctrl - h : yabai -m window --focus west
cmd + ctrl - j : yabai -m window --focus south
cmd + ctrl - k : yabai -m window --focus north
cmd + ctrl - l : yabai -m window --focus east

# Change Window Sizes
cmd + alt - h : \
  yabai -m window --resize left:-30:0; \
  yabai -m window --resize right:-30:0

cmd + alt - j : \
  yabai -m window --resize bottom:0:30; \
  yabai -m window --resize top:0:30

cmd + alt - k : \
  yabai -m window --resize top:0:-30; \
  yabai -m window --resize bottom:0:-30; \

cmd + alt - l : \
  yabai -m window --resize right:30:0; \
  yabai -m window --resize left:30:0; \

# rotate tree
cmd + alt - r : yabai -m space --rotate 90
# mirror tree y-axis
cmd + alt - y : yabai -m space --mirror y-axis

# toggle window fullscreen zoom
cmd + alt - f : yabai -m window --toggle zoom-fullscreen

# toggle window native fullscreen
cmd + alt + shift - f : yabai -m window --toggle native-fullscreen

# toggle window split type
cmd + alt - e : yabai -m window --toggle split

# float / unfloat window
cmd + alt - t : yabai -m window --toggle float

# Layouts
cmd + alt - z : yabai -m space --layout bsp
cmd + alt - x : yabai -m space --layout float

# Toggle between float && bsp
cmd + alt - space : yabai -m space --layout $(yabai -m query --spaces --space | jq -r 'if .type == "bsp" then "float" else "bsp" end')

# Relative Switching
alt - right : yabai -m space --focus next
alt - left : yabai -m space --focus prev

# toggle sticky (show on all spaces)
alt - up : yabai -m window --toggle sticky

# toggle topmost (keep above other windows)
cmd + alt - o : yabai -m window --toggle topmost

# toggle picture-in-picture
cmd + alt - p : yabai -m window --toggle pip;\
                yabai -m window --toggle topmost;\
                yabai -m window --toggle sticky
